Create Assignment, Attendance, Attendance-row & Attendance-table #54
tatuga-camp/client-main-tatugaschool pull request #5
Opened 2024-09-02 18:28 UTC by ChunWarayut

2024-09-03 09:47 UTC, permlap-phola requested changes
assignment service ทำไมมาอยู่ใใน attendance-table services

2024-09-03 09:48 UTC, permlap-phola requested changes

2024-09-03 09:48 UTC, permlap-phola commented on services/attendance-table.ts
> +}
assignment service ทำไมมาอยู่ใใน attendance-table services

2024-09-03 10:02 UTC, permlap-phola requested changes
รบกวนแก้เสร็จภายในวันนี้นะครับ

2024-09-03 10:02 UTC, permlap-phola commented on services/assignments.ts
> +): Promise<ResponseGetAssignmentsService[]> {
parameter ของ function นี้ให้แก้เป็น object parameter ทั้งหมด

2024-09-03 10:02 UTC, permlap-phola commented on services/assignments.ts
> +): Promise<ResponseGetAssignmentByIdService> {
parameter ของ function นี้ให้แก้เป็น object parameter ทั้งหมด

2024-09-03 10:02 UTC, permlap-phola commented on services/assignments.ts
> +): Promise<ResponseDeleteAssignmentService> {
parameter ของ function นี้ให้แก้เป็น object parameter ทั้งหมด

2024-09-03 10:02 UTC, permlap-phola commented on services/assignments.ts
> +): Promise<ResponseGetAssignmentsService[]> {
```
input : {subjectId : string}
```

2024-09-03 10:02 UTC, permlap-phola commented on services/attendance.ts
> +): Promise<Attendance> {
parameter ของ function นี้ให้แก้เป็น object parameter ทั้งหมด

2024-09-05 07:04 UTC, permlap-phola commented
@ChunWarayut  ช่วยแก้ไขให้หน่อยได้ไหมครับ ขอภายในศุกร์นี้ยิ่งดีครับ

2024-09-06 05:37 UTC, ChunWarayut commented
ลองเช็คหน่อยครับ

2024-09-07 08:30 UTC, permlap-phola approved these changes
Look good

2024-09-07 08:31 UTC, merged