Implement/service/part2
tatuga-camp/client-main-tatugaschool pull request #7
Opened 2024-09-10 09:55 UTC by warodompom

2024-09-11 16:49 UTC, permlap-phola requested changes
รบกวนขอภายในวันศุกร์ได้ไหมครับ
email มันไม่แจ้งเตือนเวลาพวกพี่สร้าง pull request มาเพราะใน Pull request ไม่ได้มี mention  ถึง email ผม 
ต่อไปเวลา update อะไร อย่าลืม mention email ผมด้วยนะครับ ขอบคุณครับ @ChunWarayut  @warodompom

2024-09-11 16:49 UTC, permlap-phola commented on services/ file-on-student-assignment.ts
> +};
import interface มา import { FileOnStudentOnAssignment } from "../interfaces";

2024-09-11 16:49 UTC, permlap-phola commented on services/ file-on-student-assignment.ts
> +type ResponseGetFileOnStudentAssignmentsService = ResponseCreateFileOnStudentAssignmentsService[];
แก้เป็น ResponseGetFileOnStudentAssignmentsService = FileOnStudentOnAssignment[]

ไม่ควร referance type จาก function อื่น ที่ไม่เกี่ยวข้องกัน

2024-09-11 16:49 UTC, permlap-phola commented on services/ file-on-student-assignment.ts
> +}
Type response ของแต่ละ function ควรเอาไว้ ด้านบนของ fucntion นั้นๆ จะได้หาง่าย

2024-09-11 16:49 UTC, permlap-phola commented on services/ file-on-student-assignment.ts
> +}
Endpoint นี้ไม่ได้ return void นะครับ ผมทำ ตัวอย่าง Response ของ endpoint นี้ลง POSTMAN แล้ว ดูด้วยครับ ถ้าไม่เห็นแจ้งมาได้นะครับ

2024-09-11 16:49 UTC, permlap-phola commented on services/ file-on-student-assignment.ts
> +  }
อันนี้เช่นกัน endpont ไม่ได้ return void

2024-09-11 16:49 UTC, permlap-phola commented on services/class.ts
> +};
import Interface มาครับ ไม่ต้องสร้าง type ใหม่

2024-09-11 16:49 UTC, permlap-phola commented on services/class.ts
> +};
แนะนำให้ สร้าง `Pagination<T>` เป็น type กลางเหมือนฝั่ง backend ดีกว่าครับจะได้ไม่ได้มานั่งแก้ทุกตัว เวลา update อะไร

2024-09-11 16:49 UTC, permlap-phola commented on services/class.ts
> +};
Import Interface มา ใน folder Interface

2024-09-11 16:49 UTC, permlap-phola commented on services/class.ts
> +};
Import Interface มา ใน folder Interface

2024-09-11 16:49 UTC, permlap-phola commented on services/class.ts
> +};
Import Interface มา ใน folder Interface

2024-09-11 16:49 UTC, permlap-phola commented on services/comment-assignment.ts
> +};
Import Interface มา ใน folder Interface

2024-09-11 16:49 UTC, permlap-phola commented on services/comment-assignment.ts
> +}
ไม่ควร Referance type จาก function อื่นที่ไม่ได้เกี่ยวของกัน

2024-09-11 16:49 UTC, permlap-phola commented on services/comment-assignment.ts
> +
ไม่ควร Referance type จาก function อื่นที่ไม่ได้เกี่ยวของกัน

2024-09-11 16:49 UTC, permlap-phola commented on services/file-assignment.ts
> +};
Import Interface มา ใน folder Interface

2024-09-11 16:49 UTC, permlap-phola commented on services/member-on-school.ts
> +};
Import Interface มา ใน folder Interface

2024-09-11 16:49 UTC, permlap-phola commented on services/schools.ts
> +};
Import Interface มา ใน folder Interface

2024-09-11 16:49 UTC, permlap-phola commented on services/schools.ts
> +}
อันนี้ return {message:string} 
ผมลืม save ตัวอย่างใน Postman พลาดเอง

2024-09-11 16:49 UTC, permlap-phola commented on services/score-on-student.ts
> +};
Import Interface มา ใน folder Interface

2024-09-11 16:49 UTC, permlap-phola commented on services/score-on-subject.ts
> +};
Import Interface มา ใน folder Interface

2024-09-11 16:49 UTC, permlap-phola commented on services/task.ts
> +};
ควร point ไปที่ interfaces ที่สร้างไว้แล้ว

2024-09-11 16:49 UTC, permlap-phola commented on services/task.ts
> +};
Import Interface มา ใน folder Interface

2024-09-13 15:39 UTC, ChunWarayut commented
@permlap-phola push ไปแล้วนะครับ

2024-09-13 15:42 UTC, permlap-phola commented
ขอบคุณครับพรุ่งนี้เดี๋ยวจักการให้ครับ

2024-09-14 08:25 UTC, permlap-phola approved these changes
Look good to me

2024-09-14 08:25 UTC, merged